---
Web:
  port: 9009

Client:
  appName: olleMonitor
  apiUrlStart: "/api/bitcoind"
  pageName: "OlleNature Chain (ONC)"

RPC:
  host: 127.0.0.1
  port: 9112
  rpc_username: bitcoinrpc
  colored_address: 1LXZp1j9U6VBUfKvqYtFrpDhE5r1LFijw1
  concurrency: 100

Zmq:
  socket: "tcp://127.0.0.1:28332"
  events:
    - "hashblock"
    - "hashtx"
    - "rawblock"
    - "rawtx"
    
Bitcoin:
  homeDir: '/Users/roy/1/'

Api:
  restCalls:
    - callName: getinfo
      inputName: none
      inputType: none
      uri: '/getinfo'
    - callName: getpeerinfo
      inputName: none
      inputType: none
      uri: '/getpeerinfo'
      timeout: 4000
    - callName: getblockchaininfo
      inputName: none
      inputType: none
      uri: '/getblockchaininfo'
      timeout: 8000
    - callName: getnetworkinfo
      inputName: none
      inputType: none
      uri: '/getnetworkinfo'
    - callName: getmempoolinfo
      inputName: none
      inputType: none
      uri: '/getmempoolinfo'
    - callName: getrawmempool
      inputName: none
      inputType: none
      uri: '/getrawmempool'
      timeout: 4000
    - callName: getmempoolentry
      inputName: hash
      inputType: string
      uri: '/getmempoolentry/:hash'
    - callName: getblockhash
      inputName: index
      inputType: number
      uri: '/getblockhash/:index'
    - callName: getblock
      inputName: hash
      inputType: string
      uri: '/getblock/:hash'
    - callName: estimatefee
      inputName: nblocks
      inputType: number
      uri: '/estimatefee/:nblocks'
    - callName: getrawtransaction
      inputName: txid
      inputType: string
      uri: '/getrawtransaction/:txid'
      verbose: true
    - callName: getblockcount
      inputName: none
      inputType: none
      uri: '/getblockcount'
...
